### PR TITLE
feat(workflows): Add linting GitHub Actions

### PR DESCRIPTION
**Pull request by gabrielmocanu**
- Add super-linter action for linting source-code and Markdown files.
- Add spellcheck action to check for misspellings in Markdown files.

### CODE REVIEW

**Comment by craciunoiuc** [comment]
Can you make this also run on commit messages? Would be useful on multiple repos

**Comment by razvand** [comment]
> Can you make this also run on commit messages? Would be useful on multiple repos

@craciunoiuc , you mean linting commit messages? Such as commit message length, use of prefix and others?

**Comment by craciunoiuc** [comment]
Question was more directed to the spellchecker. There are always typos in commit messages and are hard to point out.

For sure one hacky way would be to write the messages to files and let the spellchecker catch them

**Comment by craciunoiuc** [comment]
Question was more directed to the spellchecker. There are always typos in commit messages and are hard to point out.

For sure one hacky way would be to write the messages to files and let the spellchecker catch thema

**Comment by razvand** [comment]
@gabrielmocanu , is it possible to spellcheck commit messages? We can do that in a separate PR.

**Comment by gabrielmocanu** [comment]
> @gabrielmocanu , is it possible to spellcheck commit messages? We can do that in a separate PR.

Yup, it's possible, but please make another issue and assign it to me. I will do another PR for it.

**Review by razvand — APPROVED** [review]

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
