### PR TITLE
docs(redis/7.0): Indicate min memory requirement

### PR DESCRIPTION
**Pull request by ChaoyiHuang**
Minimal memory size is 128M
Also update the readme to include build the image locally

### CODE REVIEW

**Review by nderjung — COMMENTED** [review]
Hi @ChaoyiHuang! Thanks so much for the contribution! Can I just ask you to reword your commit:

```
docs(redis/7.0): Indicate min memory requirement

Minimal memory size is 128M.
Also update the readme to include build the image locally.

GitHub-Closes: #58
```

Thanks!

**Comment by ChaoyiHuang** [comment]
Sure, will do

**Review by nderjung — APPROVED** [review]
Thanks!

**Pull request merged**
