### PR TITLE
feat(library): Introduce R 4.3.3 as library entry

### PR DESCRIPTION
**Pull request by Mihnea0Firoiu**
## Introduce R helloworld example.

 The Docker works as expected, with the output:
 ```[1] "Hello, World!"```

Check with multiple options for the `-M` flag when using `kraft run`:

1. For no option: ```E  machine fatally exited```
2. For **256M**: 
```
[    0.219079] CRIT: [libvfscore] Failed to extract cpio archive to /: -3
[    0.219337] ERR:  [libukboot] Init function at 0x14adc0 returned error -5
 E  machine fatally exited
 ```
 3. For **768M**:
 ```
Rscript execution error: Function not implemented
 ```

### CODE REVIEW

**Comment by razvand** [comment]
@Mihnea0Firoiu , did you enable system calls?

I would suggest you add this as a `library/` item. And when you create the `Kraftfile` for that (use any existing `Kraftfile`, i.e. [`Nginx`](https://github.com/unikraft/catalog/blob/main/library/nginx/1.25/Kraftfile), uncomment the ` # CONFIG_LIBSYSCALL_SHIM_STRACE: 'y'` line. And that will provide you extensive info.

Also document this problem as an issue, following [the others](https://github.com/unikraft/catalog/issues).

**Comment by Mihnea0Firoiu** [comment]
@razvand Should I keep the name `helloworld-r` for the directory when I introduce it as a `library/` item or should I change it to `R/4.3.3` ?

**Comment by razvand** [comment]
> @razvand Should I keep the name `helloworld-r` for the directory when I introduce it as a `library/` item or should I change it to `R/4.3.3` ?

Change it to `r/4.3.3`.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
